/**
 * Примеры для сторибука ядра (npm run storybook → dist/storybook.html).
 * Один пример — один типичный вызов компонента с правдоподобными данными.
 * Новый компонент в components.mjs без примера здесь — сторибук это покажет.
 */
export const groups = [
  { title: 'Шапки', items: [
    { name: 'top', note: 'Корень вкладки: бренд или профиль слева, иконки справа', render: (ui) => ui.top(ui.wordmark({ name: 'Образы', logo: 'looks/assets/app-icon.png' }), [ui.iconButton({ icon: 'search', label: 'Поиск' }), ui.iconButton({ icon: 'plus', label: 'Новая публикация' })]) },
    { name: 'largeTitle', note: 'Корень вкладки с заголовком 24/30', render: (ui) => ui.largeTitle('Мессенджер', ui.iconButton({ icon: 'square-pen', label: 'Новое сообщение' })) },
    { name: 'nav', note: 'Вложенный экран: назад · заголовок · действие', render: (ui) => ui.nav({ title: 'Публикация', trailing: ui.iconButton({ icon: 'share', label: 'Поделиться' }) }) },
    { name: 'me', note: 'Профиль в шапке', render: (ui) => ui.top(ui.me({ name: 'Марина', initial: 'М' })) },
  ] },
  { title: 'Кнопки', items: [
    { name: 'button', note: 'primary · secondary · tertiary; l 44 и m 36', render: (ui) => ui.actions([ui.button({ label: 'Ждать результат', block: true }), ui.button({ label: 'Показать ведущей', icon: 'message-circle', variant: 'secondary', block: true }), ui.button({ label: 'Не сейчас', variant: 'tertiary', block: true })]) },
    { name: 'actions row', note: 'Две кнопки в ряд', render: (ui) => ui.actions([ui.button({ label: 'Редактировать', variant: 'secondary' }), ui.button({ label: 'Поделиться', variant: 'secondary' })], { row: true }) },
    { name: 'iconButton · textButton · play', note: 'Иконка 24 в зоне 44; текстовая кнопка шапки; play трёх размеров', render: (ui) => `<div class="sb-row">${ui.iconButton({ icon: 'heart', label: 'Нравится' })}${ui.iconButton({ icon: 'plus', look: 'fill', label: 'Добавить' })}${ui.textButton({ label: 'Готово', strong: true })}${ui.play({ size: 's', label: 'Играть' })}${ui.play({ label: 'Играть' })}${ui.squareButton({ icon: 'download', label: 'Скачать' })}</div>` },
  ] },
  { title: 'Списки и секции', items: [
    { name: 'section · list · row', note: 'Строка 64: значок, обложка или аватар · две строки · хвост', render: (ui) => ui.section({ title: 'На месте', more: { label: 'Все' }, children: ui.list([
      ui.row({ lead: ui.leadIcon('map-pin', { accent: true }), title: 'Отметиться на свопе', sub: 'После входа во двор Бутылки', go: 'x' }),
      ui.row({ lead: ui.leadIcon('', { text: '19:30' }), title: 'Разбор гардероба', sub: 'Рубинштейна · 1,2 км', end: { badge: 'идёт' } }),
      ui.row({ lead: ui.avatar('ЛС'), title: 'Лера Савина', sub: '18 общих подписок', end: { value: 'Написать', toast: 'x', label: 'Написать' }, go: 'x' }),
      ui.row({ thumb: 'ph', title: 'Чечевичный суп', sub: '35 минут', duration: '2:40' }),
    ]) }) },
    { name: 'group · cell', note: 'Настройки: белые группы на сером, свитч, значение, шеврон', render: (ui) => ui.section({ children: ui.group({ label: 'Уведомления', cells: [
      ui.cell({ icon: 'bell', title: 'Подписки', sub: '12 авторов', toggle: true }),
      ui.cell({ icon: 'megaphone', title: 'Реклама', value: 'Без подбора', go: 'x' }),
      ui.cell({ icon: 'scan-face', title: 'Замок Face ID', toggle: false }),
    ] }) }) },
    { name: 'checklist', note: 'Чек-лист: отметка на месте, отмеченное зачёркнуто', render: (ui) => ui.section({ title: 'Купить заранее', meta: '2 из 4', children: ui.checklist([{ title: 'Мука', sub: '1 кг · куплено', done: true }, { title: 'Лук', done: true }, { title: 'Фарш говяжий', sub: '700 г' }, { title: 'Сметана · 2 банки' }]) }) },
    { name: 'foot', note: 'Подпись под секцией: когда сверено, сколько всего', render: (ui) => ui.section({ title: 'Счётчики', children: [ui.list([ui.row({ lead: ui.leadIcon('droplets'), title: 'Горячая вода', sub: '00412,38 м³' })]), ui.foot('Сверено сегодня в 9:12 · 214 номеров')] }) },
    { name: 'stats', note: 'Счётчики профиля', render: (ui) => ui.section({ children: ui.stats([['86', 'публикаций'], ['312', 'подписчиков'], ['148', 'подписок']]) }) },
    { name: 'search · chips · segments', note: 'Поиск; чипсы — переходы; сегменты внутри экрана', render: (ui) => ui.section({ children: [ui.search({ placeholder: 'Поиск по сообщениям' }), '<div class="sb-gap"></div>', ui.chips([{ label: 'Все', on: true }, { label: 'Быстро' }, { label: 'Выпечка' }]), '<div class="sb-gap"></div>', ui.segments([{ label: 'Для вас', on: true }, { label: 'Обновления' }])] }) },
  ] },
  { title: 'Доступы', items: [
    { name: 'denied', note: 'Отказ в доступе, без которого фича не работает: пустое состояние iOS и вход в Настройки', render: (ui) => ui.denied('camera').replace('perm-hidden ', '') },
  ] },
  { title: 'Меню', items: [
    { name: 'menu', note: 'Сервисы двумя колонками, как в меню ВК', render: (ui) => ui.menu([{ icon: 'images', label: 'Мои серии' }, { icon: 'users', label: 'Авторы', badge: 3 }, { icon: 'tv', label: 'Выставка' }, { icon: 'lock', label: 'Черновики' }, { icon: 'shield', label: 'Приватность' }, { icon: 'chevron-right', label: 'Ещё' }]) },
  ] },
  { title: 'Сведения о событии и людях', items: [
    { name: 'miniInfo · usersStack', note: 'Событие как в ВК: факты строками со значком и кто идёт', render: (ui) => ui.miniInfo([{ icon: 'calendar', text: 'Сегодня, 19:30 · 75 минут', accent: true }, { icon: 'map-pin', text: 'Клуб «Полка», Абая 44' }, { icon: 'info', text: 'Подробнее', more: true, toast: 'x' }]) + ui.usersStack({ faces: ['МО', 'ИЛ', 'ЖК'], text: 'Маша, Илья и ещё 2 идут', toast: 'x' }) },
    { name: 'infoRows', note: 'Паспорт вещи, адрес, реквизиты', render: (ui) => ui.infoRows([['Инвентарный номер', '074'], ['Мастерская', 'Реверс, 13-я линия В.О., 70']]) },
    { name: 'richCell', note: 'Заявка или приглашение: текст и кнопки под ним', render: (ui) => ui.richCell({ lead: ui.avatar('ИБ'), over: 'Назначение', title: 'Ирина Бек', sub: 'Возьмёте абажур для Л‑74?', after: '19:20', actions: [{ label: 'Принять', toast: 'x' }, { label: 'Отказаться', variant: 'secondary', toast: 'x' }] }) },
    { name: 'hscroll', note: 'Карточки вбок: люди (s), места (m), события (l)', render: (ui) => ui.hscroll([{ initial: 'МЛ', title: 'Марина', toast: 'x' }, { initial: 'МК', title: 'Миша', toast: 'x' }, { initial: 'ЛЯ', title: 'Лера', toast: 'x' }, { initial: 'ПИ', title: 'Пётр', toast: 'x' }], { size: 's' }) + ui.hscroll([{ title: 'Зелёный базар', sub: '42 работы', toast: 'x' }, { title: 'Терренкур', sub: '18 работ', toast: 'x' }]) },
    { name: 'banner · placeholder · subnav', note: 'Важное с действием, пустое состояние, фильтры со значком', render: (ui) => ui.subnav([{ icon: 'calendar', label: 'Сегодня', on: true, go: 'x' }, { icon: 'map-pin', label: 'Рядом', go: 'x' }, { icon: 'users', label: 'Знакомые', count: 4, go: 'x' }]) + ui.banner({ icon: 'calendar', title: 'Пленэр завтра в 9:00', sub: 'Возьмите складной стул', button: { label: 'Я пойду', toast: 'x' } }) + ui.placeholder({ icon: 'pen-line', title: 'Черновиков нет', sub: 'Снимите рисунок — он появится здесь', button: { label: 'Новая работа', toast: 'x' } }) },
  ] },
  { title: 'Соцсеть', items: [
    { name: 'stories', note: 'Фото, инициалы или значок; просмотренные — серое кольцо', render: (ui) => ui.stories([{ label: 'История', icon: 'plus', seen: true }, { label: 'Жанна', initial: 'ЖК' }, { label: 'Вместе', icon: 'chef-hat' }, { label: 'Тимур', initial: 'ТС', seen: true }]) },
    { name: 'composerPrompt', note: '«Что нового?» над лентой', render: (ui) => ui.composerPrompt({ initial: 'СЛ', placeholder: 'Что получилось сегодня?', trailing: ui.iconButton({ icon: 'camera', label: 'Снять' }) }) },
    { name: 'post', note: 'Пост: автор, текст, вложение, реакции. Без фото — без пустого кадра', render: (ui) => ui.post({ author: { initial: 'ЖК', name: 'Жанна Ким', meta: 'сегодня, 12:14 · Алматы' }, text: 'Тот самый чечевичный суп, но без сливок', attach: ui.list([ui.row({ lead: ui.leadIcon('utensils'), title: 'Чечевичный суп', sub: '35 минут · проверили 34 раза' })]), likes: 126, comments: 18, shares: 9, views: '4,1K', menu: ['Скрыть', 'Пожаловаться'] }) },
    { name: 'entry', note: 'Своя запись в ленте: фото, голос, статус и действия — без лайков и чужих авторов', render: (ui) => ui.entry({ icon: 'wrench', title: 'Доводчик на второй двери', meta: 'сегодня, 8:12 · заявка', status: { label: 'в работе', accent: true }, text: 'Сорвало, бьёт по коляскам. Мастер обещал с 16:00', photos: 2, actions: [{ label: 'Отправить в чат УК', icon: 'send', toast: 'x' }], menu: ['Изменить', 'Удалить'] }) + ui.entry({ icon: 'mic', title: 'Что сказать сантехнику', meta: 'вчера, 21:40 · заметка', voice: { dur: '0:24' } }) },
    { name: 'comments', note: 'Комментарии под постом: ответ с отступом, метка автора, лайк справа', render: (ui) => ui.comments({ count: 9, items: [{ initial: 'РЛ', name: 'Роман Ли', text: 'На мосту сегодня в 7 утра тоже скользко', time: '22:17', likes: 6 }, { initial: 'АВ', name: 'Алина Ветрова', text: 'Спасибо, поведу группу по велодорожке', time: '22:40', likes: 2, reply: true, author: true }, { initial: 'ЛЮ', name: 'Лера Юдина', text: 'Темп 6:12 чистый или с остановками?', time: '8:03', liked: true, likes: 1 }] }) },
  ] },
  { title: 'Системные поверхности', items: [
    { name: 'homeScreen · pip', note: '«Картинка в картинке» поверх «Домой»: окно видео, значки, док', render: (ui) => '<div class="ui-hs" style="position:relative;height:760px;border-radius:16px;overflow:hidden">' + ui.homeScreen({ app: { name: 'Вратарь', icon: 'trophy', go: 'x' }, pip: { open: { go: 'x' } } }) + '</div>' },
    { name: 'homeScreen', note: 'Экран «Домой» с виджетом приложения: appgroups и keychain', render: (ui) => `<div class="ui-hs" style="padding:0 0 12px">${ui.homeScreen({ widget: { icon: 'chef-hat', kicker: 'Вкусно · сейчас', title: 'Шаг 2 из 6 · обжарить лук', sub: 'Таймер 5:42', toast: 'x' }, app: { name: 'Вкусно', icon: 'chef-hat', toast: 'x' } })}</div>` },
    { name: 'safariFill', note: 'Safari с подсказкой пароля над клавиатурой: autofill', render: (ui) => `<div class="ui-sf" style="position:relative;padding-bottom:72px">${ui.safariFill({ site: 'arbuz.kz', title: 'Вход в доставку', sub: 'Заказы и адреса', fields: [['Телефон', '+7 701 ··· 44 17', true], ['Пароль', '••••••••']], suggestion: { app: 'Вкусно', login: '+7 701 ··· 44 17' } })}</div>` },
  ] },
  { title: 'Мессенджер', items: [
    { name: 'dialog', note: 'Строка диалога: онлайн, непрочитанные, «Вы:»', render: (ui) => [ui.dialog({ initial: 'ЛС', name: 'Лера Савина', text: 'Покажете жакет?', time: '9:36', unread: 2, online: true }), ui.dialog({ initial: 'ТС', name: 'Тимур Садыков', text: 'Рецепт · Хачапури', time: 'пн', you: true })].join('') },
    { name: 'chatNav · chat · bubble · voice · composer', note: 'Чат целиком', render: (ui) => ui.chatNav({ initial: 'ЛС', name: 'Лера Савина', status: 'в сети', call: { toast: 'x' } }) + ui.chat([ui.day('Сегодня'), ui.bubble({ text: 'Вещи принимаю до 10:00', time: '9:20' }), ui.bubble({ out: true, text: 'Вот жакет, размер 46', time: '9:28', read: true }), ui.voice({ dur: '0:09', time: '9:37' })]) + ui.composer({ mic: { toast: 'x' } }) },
    { name: 'callView', note: 'Звонок: аватар, статус, круглые кнопки', render: (ui) => ui.callView({ initial: 'ЛС', name: 'Лера Савина', status: 'Проверка: жакет · 00:48', controls: [{ icon: 'mic-off', label: 'Микрофон' }, { icon: 'video', label: 'Камера' }, { icon: 'phone-off', label: 'Завершить', end: true }] }) },
  ] },
  { title: 'Медиа', items: [
    { name: 'card · shelf', note: 'Карточки ленты Музыки', render: (ui) => ui.shelf([ui.card({ art: 'ph', title: 'Тихий берег', sub: '6 сессий' }), ui.card({ art: 'ph', title: 'Синий час', sub: '12 мин' }), ui.card({ art: 'ph', title: 'Под водой', sub: '5 мин' })]) },
    { name: 'grid', note: 'Сетка карточек 2 в ряд', render: (ui) => ui.grid([ui.card({ art: 'ph', title: 'Сторона А', sub: '7 треков' }), ui.card({ art: 'ph', title: 'Сторона Б', sub: 'откроется после А' })]) },
    { name: 'player', note: 'Плеер ВК Видео: управление поверх кадра, главы на шкале — свои у каждого продукта', render: (ui) => ui.player({ art: 'ph', at: '2:06', total: '7:24', fillClass: 'sb-w-40', chapters: [{ label: 'Контекст', w: 2, state: 'done' }, { label: 'Проблема', w: 2, state: 'done' }, { label: 'Решение', w: 4, state: 'now' }, { label: 'Шаг', w: 2 }], chapter: 'Решение · +38 с', collapse: { back: true }, cast: { toast: 'x' }, settings: { toast: 'x' }, pip: { toast: 'x' }, fullscreen: { toast: 'x' } }) },
    { name: 'videoCard', note: 'Видео 16:9 с длительностью и прогрессом', render: (ui) => `<div class="sb-pad">${ui.videoCard({ art: 'ph', duration: '18:40', title: 'Выходные у озера', sub: '38 видео · собрано 58 %' })}</div>` },
    { name: 'tiles', note: 'Плитки-входы 2 в ряд', render: (ui) => ui.tiles([{ title: 'Подборки', sub: '12', art: 'ph' }, { title: 'Скачанное', sub: '3', art: 'ph' }]) },
    { name: 'clip', note: 'Вертикальный клип как в ВК Клипах: кадр во весь экран, колонка действий, автор и название', render: (ui) => '<div class="ui ui-clips" style="position:relative;height:720px;border-radius:16px;overflow:hidden;--safe-bottom:0px">' + ui.clip({ top: 'Клипы', sub: 'Вечер у Лены · 1 из 14', author: { initials: 'ОМ', name: 'Оля' }, title: 'Утро понедельника без слов', meta: 'раунд 1 · 0:09 · вчера', rail: [{ icon: 'heart', label: 'Нравится', count: '3', toggle: 'on' }, { icon: 'trophy', label: 'Голос', count: 'Голос', toggle: 'on' }, { icon: 'tv', label: 'На ТВ', go: 'x' }, { icon: 'share', label: 'Поделиться', toast: 'x' }] }) + '</div>' },
    { name: 'musicControls', note: 'Полноэкранный аудиоплеер: название, шкала, назад · play · вперёд, переключатели на месте', render: (ui) => '<div style="padding:0 24px 16px">' + ui.musicControls({ title: 'Припев про дождь · v3', sub: 'диктофон, дома · 2 августа', at: '0:57', left: '−1:50', pct: 34, bottomLeft: { icon: 'lock', label: 'Слушать в фоне', toast: 'x' }, bottomRight: { icon: 'list-music', label: 'Все версии', toast: 'x' } }) + '</div>' },
    { name: 'lockScreen', note: 'Экран блокировки iOS: дата, время, уведомления, «Сейчас играет», фонарик и камера', render: (ui) => '<div class="ui-lock" style="position:relative;height:720px;border-radius:16px">' + ui.lockScreen({ time: '16:05', date: 'среда, 7 октября', notifications: [{ title: 'Мама', initials: 'РХ', text: 'Позвони, как Милу заберёшь', time: '15:21', go: 'x' }, { title: 'Тимур Гарипов', app: 'Гариповы', initials: 'ТГ', text: 'Задержусь до 19:30', time: '15:58', go: 'x' }], nowPlaying: { title: 'Голосовое мамы, 3 из 4', sub: 'Роза · 2:31', at: '1:12', left: '−1:19', fillClass: 'sb-w-40', go: 'x' } }) + '</div>' },
    { name: 'photoPicker', note: 'Выбор фото iOS: лист, сегменты, поиск, сетка 3 в ряд, номер выбора', render: (ui) => '<div style="position:relative;height:640px;border-radius:16px;overflow:hidden;background:#000">' + ui.photoPicker({ section: 'Недавние', tiles: [{ picked: 1 }, {}, { duration: '0:14', picked: 2 }, {}, {}, { duration: '0:41' }, {}, {}, {}, {}, { duration: '1:02' }, {}], add: { toast: 'x' } }) + '</div>' },
    { name: 'homeScreen', note: 'Экран «Домой» iOS: виджет с подписью, значки 4 в ряд, «Поиск», док', render: (ui) => '<div class="ui-hs" style="position:relative;height:760px;border-radius:16px;overflow:hidden">' + ui.homeScreen({ widget: { icon: 'house', kicker: 'Кто дома', title: 'Даня дома с 15:40', sub: 'Мила на рисовании до 17:30', go: 'x' }, app: { name: 'Все дома', icon: 'house', go: 'x' } }) + '</div>' },
    { name: 'adCard · reminder', note: 'ATT с видимым подбором; push у своего события', render: (ui) => ui.section({ children: [ui.list([ui.reminder({ title: 'Напомнить о прогоне накануне', titleGranted: 'Напомним в среду в 20:00', sub: 'Накануне выступления, 12 августа', here: 'x' })]), ui.adCard({ icon: 'mic', title: 'Петличка за 1 990 ₽', sub: 'Реклама · без подбора', subGranted: 'Реклама · по интересам', go: 'x' })] }) },
    { name: 'miniPlayer · tabBar', note: 'Нижняя панель корня', render: (ui) => ui.tabBar({ items: [{ id: 'home', label: 'Главная', icon: 'house' }, { id: 'chats', label: 'Мессенджер', icon: 'message-circle' }, { id: 'profile', label: 'Профиль', icon: 'user' }], active: 'home', mini: ui.miniPlayer({ face: 'ph', title: 'Тихий берег', sub: 'выдох 6 с', open: {}, playAction: { label: 'Играть' }, progressClass: 'sb-w-40' }) }) },
  ] },
];
